/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://vwwrxb2q7verjdfu5ktdiod7pm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-2:39031bd3-d2ba-4ae5-b431-cd166b7fe1b6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_P7kmKO8QD",
    "aws_user_pools_web_client_id": "3dr37379i70c5v6jab3pi64lkr",
    "oauth": {}
};


export default awsmobile;